### ISSUE TITLE
Large XML files slow/memory timeout

### ISSUE THREAD

**Issue by edwinvdpol** [nullivex/lib-array2xml#10]
The XML2Array is fun and works great with small XML files 👍  But, when you try to convert and 100MB+ XML file, your machine will run out of memory. When you increase the memory limit, it takes forever (way too long). 2048MB isn't enough. Too bad, because it works like a charm!

I tried searching for other XML2Array classes, but unfortunately no success.
Anyone else has suggestions?

**Comment by nullivex** [comment]
I dont believe this performance issue can be addressed easily to the nature of how PHP structures Objects (they are hugely memory intensive). Closing this due to little recourse.
