### ISSUE TITLE
Array can't contain number?

### ISSUE THREAD

**Issue by chan15** [nullivex/lib-array2xml#2]
``` php
$array = array(
            0 => array(
                'id' => 1,
                'name' => 'Chan'
            ),
            1 => array(
                'id' => 2,
                'name' => 'Phoebe'
            ),
        )
```

If I put this array to `$xml = Array2XML::createXML('root', $array);`, and output `$xml->saveXML();`, I got error message `error on line 1 at column 1: Document is empty`, how to not use number as loop array data?

**Comment by nullivex** [comment]
@chan15 Surround the number in quotes will do the trick. I believe literals might not work right being coerced to XML.

This is also very old so maybe it has been corrected.
